### ISSUE TITLE
Need for specific functions

### ISSUE THREAD

**Issue by paladinkolovrat** [ianpatt/f4se#10]
Hi!
Can I ask for some features like:
-Check door opening
-Check container opening
-Check item grabbing

We're working on animation mod - animating ingestible item for 1st and 3rd person(like in Escape From Tarkov, for example). We tried to make features up here but didn't succeed. It cannot be achieved by scripts, maybe .dll plugin can do something but this is out of our abilities.

Thank you in advance!

**Comment by Scrivener07** [comment]
Much of this sounds achievable with vanilla capabilities. Expect that a new papyrus function request will be scrutinized.

Opening & Closing
https://www.creationkit.com/fallout4/index.php?title=OnActivate_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnOpen_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnClose_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnAnimationEvent_-_ScriptObject

Grabbing
https://www.creationkit.com/fallout4/index.php?title=GetPlayerGrabbedRef_-_Game
https://www.creationkit.com/fallout4/index.php?title=OnGrab_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnRelease_-_ObjectReference

Containers
https://www.creationkit.com/fallout4/index.php?title=OnContainerChanged_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnItemAdded_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnItemRemoved_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnEquipped_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnUnequipped_-_ObjectReference
https://www.creationkit.com/fallout4/index.php?title=OnItemEquipped_-_Actor
https://www.creationkit.com/fallout4/index.php?title=OnItemUnequipped_-_Actor

Animated items have also been achieved if you search existing mods.

**Comment by niston** [comment]
Also, for to get open state of an object, you can use GetOpenState():
[](https://www.creationkit.com/fallout4/index.php?title=GetOpenState_-_ObjectReference)
