### ISSUE TITLE
To get f4se working on Linux/proton/steam

### ISSUE THREAD

**Issue by picobyte** [ianpatt/f4se#15]
In Linux, the steam properties-> launch option solution posted on reddit is incorrect. To get f4se version 0.06.21 working,  these instructions do seem to work:
```
1) Go to your Fallout 4 folder, which most likely is -"C:\Program Files(x86)\Steam\Steamapps\Common\Fallout4\"
2) Rename the Fallout4.exe to F4.exe
3) Rename f4se_loader.exe to Fallout4.exe
4) Go to \data\f4se\ - if the f4se folder doesn't exist, create it.
5) Make a file called f4se.ini and write this in it

[Loader]
RuntimeName=F4.exe

6) Save file
7) Start Fallout 4 via steam and hit Play
```
source: https://steamcommunity.com/sharedfiles/filedetails/?id=682660057

How to test whether f4se is working?
the f4se version must be listed in the game settings (below in the menu where you can start a new game)
from: https://www.reddit.com/r/fo4/comments/7d0upr/not_sure_f4se_is_workinghow_can_i_test/
It should look like this:
https://vignette.wikia.nocookie.net/warhammerfb/images/b/b4/512512341241234124.PNG/revision/latest?cb=20171111063229
if you don't see F4SE version listed, it is not working.

**Comment by ianpatt** [comment]
You seem to be reporting an issue with a third-party post on reddit. This is not the right place to do that. I have no idea who made the post you are referring to, but you should talk with them about it.

**Comment by picobyte** [comment]
The reddit post is archived [1] and cannot be edited or commented on. It is the first thing that pops up on google with the right terms and it is unclear that f4se is non-functioning unless you know where to look. the instructions in the f4se readme are not helping If it could be listed there this saves some trouble.
[1] https://www.reddit.com/r/linux_gaming/comments/e07pm8/fallout_4_modding_f4se_works_on_unpatched_proton/

**Comment by ianpatt** [comment]
For what it's worth, you shouldn't need to do any of these steps either. If Proton is working properly, you should just be able to run f4se_loader like a normal user and have everything work. These steps are just making it so that when you click the Fallout 4 button, it launches f4se_loader instead.

**Comment by picobyte** [comment]
Thanks for your suggestion. I can add a launcher for a Linux binary via 'Add a game' -> 'Add a non-steam Game' but it doesn't list windows .exe's. I think I tried adding a bash wrapper script and this didn't work. What I've listed works for me. Maybe you're right and this isn't the place. Thanks anyway.

**Comment by picobyte** [comment]
FWIW, after a fresh install of Fallout 4 (from a backup). Using a steam launcher for f4se_loader, after first running the game normally once, I do not get the splash screen (with e.g. play/options/support/exit), also only some sounds, no main-menu or voice sounds, although movie sounds are heard. Also I get a smaller window, non-maximized, in contrast to running the game normally.

Possibly ini files are not loaded. What often is a problem is that Linux (or mac or android) is case sensitive, and files specified in a wrong case are not found. Either that or maybe the path slash/backslash could be the problem if the problem is this trivial.

BTW adding the Data/F4SE/f4se.ini file alone does not help, when assigning Fallout4Launcher.exe instead of Fallout4.exe, I do get to see an error message.

Settings from the main menu does indicate that f4se is active, although I do not see a shell before running. This is also different, compared to after renaming, which does work. I even get a working AAF now (home button works) which is a first for my installation. Finally making some progress..
```
if [ ! -f F4.exe ]; then
  mv Fallout4.exe F4.exe
fi
mv f4se_loader.exe Fallout4.exe
echo -e -n "[Loader]\n\rRuntimeName=F4.exe\n\r" > Data/F4SE/f4se.ini
```
HTH
