### ISSUE TITLE
game pass compatibility

### ISSUE THREAD

**Issue by celian-hamon** [ianpatt/f4se#17]
hello i "have" the game on gamepass it is exactly like the steam version except that you dont need the steam part so i can launch the game through f4se but it doesnt extend f4 so can you make a game pass version ? i can give you my gamepass code if you can make it

**Comment by ianpatt** [comment]
The gamepass version is not exactly like the Steam version. There are no plans for support.

**Comment by celian-hamon** [comment]
thank you for taking the time to reply me
