### ISSUE TITLE
"common" nested directory causing build issues

### ISSUE THREAD

**Issue by hxef** [ianpatt/f4se#18]
Since v0_06_22 the path to common libs is `f4se_0_06_23\src\common\common`, while on previous versions it's `f4se_0_06_21\src\common`, causing errors when building the "common_v11" project from latest source in Visual Studio.

I had to remove the extra "common" directory within the following vs studio files as well:
```
src\f4se\f4se.sln
src\f4se\f4se\f4se.vcxproj
src\f4se\f4se\f4se_common.vcxproj
src\f4se\f4se\f4se_loader.vcxproj
src\f4se\f4se_steam_loader\f4se_steam_loader.vcxproj
```

After these adjustments I could build successfully.

**Comment by achekerylla** [comment]
Thanks for sharing!  My workaround adds a few details that I hope are helpful to others as well.

----

If you see any build errors like "cannot open source file common/ITypes.h", then visual studio needs help finding the "common_vc11" project files.  One way to do this is to modify the source directory as described below:

1. From the solution explorer folder view, move all files and folders for the "common_vc11" project from "common/common/" to "common/".

1. From the solution explorer solution view, remove the "common_vc11" project and re-add it from its new location "common\common_vc11.vcxproj".  Remove and re-add any references to this project.

1. Now, run "Rebuild solution" to confirm the build errors have gone away.

1. Also, remove the now empty folder "common/common/".

**Comment by ianpatt** [comment]
Please use cmake to generate the project. The included MSVC projects are there for legacy reasons and aren't supported.
