### ISSUE TITLE
Xbox PC App Version

### ISSUE THREAD

**Issue by Mrnoodlez12** [ianpatt/f4se#20]
Possibility for it in 2023 Since Microsoft has enabled modding support for games within the last half year
Photo For Proof
![image_2023-06-14_230706978](https://github.com/ianpatt/f4se/assets/64455621/c87832d1-18c7-4fad-9081-ff03bc803a43)

**Comment by ianpatt** [comment]
Try modifying the executable.

**Comment by ianpatt** [comment]
To give some more detail, this happened a while ago, and changed nothing significant from a technical level. Control of launching the game is still DRM-protected, it's still a unique build of the game, and the executable is still protected.

Not happening.
