### ISSUE TITLE
2024-04-25 Fallout 4 update has broken F4SE

### ISSUE THREAD

**Issue by Diav3l** [ianpatt/f4se#23]
"The 2024-04-25 Fallout 4 update (1.10.980 and later) has broken F4SE and the rest of the native code modding scene similarly to Skyrim's "Anniversary Edition" patch. [ianpatt is] working on an update and cannot currently offer a timeline for its availability, nor whether there will be any critical technical issues that would block an update. Do not email with questions."

**Comment by ianpatt** [comment]
72cf38f8129661e46a31fd879408df570d2376c6
