### ISSUE TITLE
Buncha Questions

### ISSUE THREAD

**Issue by snowboundmage2** [ianpatt/f4se#29]
I'm very dumb when it comes to coding, so please forgive any thing that may seem obvious.
Context: I'm trying to learn f4se plugin making

Why is src/common a different git now?

Why use/define a custom UInt32 instead of just using the c++ standard of uint32_t? Same for UInt64 and so-on

**Comment by ianpatt** [comment]
This is not the intended use of an issue tracker. Send an email.
